dist: trusty
language: python
python:
  - "3.6"
sudo: required
services:
  - docker
before_install:
  - docker build -t itstommy/miley .
  - docker run -d -p 127.0.0.1:80:4567 itstommy/miley /bin/sh -c "cd /usr/src/miley"
script:
  - python manage.py test
