language: python
python:
  - "3.6"
env:
  - DJANGO=1.11.2
services:
  - postgresql
before_install:
  - export DJANGO_SETTINGS_MODULE=miley.settings
  - export PIP_USE_MIRRORS=true
install:
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE default;" -U postgres
script:
  - python manage.py test
