version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/server
    depends_on:
      - db_psql
    volumes:
      - .:/usr/src/miley
    environment:
      - DEBUG=1
      - POSTGRES_DB=miley
    ports:
      - 80:8000

  # migrations:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   depends_on:
  #     - postgres
  #   command: python manage.py migrate

  db_psql:
    image: postgres:9.6.4

  redis:
    image: redis:3.2.10
