# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, upload_to='users/%Y/%m/%d'),
        ),
    ]
