export const actionTypes = {
  CURRENT_USER: 'CURRENT_USER',
  GET_PROFILES: 'GET_PROFILES',
  GET_PROFILES_ACTIVITIES: 'GET_PROFILES_ACTIVITIES',
  RECEIVE_PROFILES: 'RECEIVE_PROFILES',
  RECEIVE_PRODUCTS: 'RECEIVE_PRODUCTS',
  REQUEST_SHOPS: 'REQUEST_SHOPS',
  RECEIVE_SHOPS: 'RECEIVE_SHOPS',
  LIKE_SHOP: 'LIKE_SHOP',
  REQUEST_TRENDS: 'REQUEST_TRENDS'
}
