export const actionTypes = {
  CURRENT_USER: 'CURRENT_USER',
  GET_PROFILES: 'GET_PROFILES',
  RECEIVE_PRODUCTS: 'RECEIVE_PRODUCTS',
  REQUEST_SHOPS: 'REQUEST_SHOPS',
  RECEIVE_SHOPS: 'RECEIVE_SHOPS',
  LIKE_SHOP: 'LIKE_SHOP',
  INCREMENT_COUNTER: 'INCREMENT_COUNTER'
}
